# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a75tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/nlao2/lab_1/lab_1.cache/wt [current_project]
set_property parent.project_path C:/Users/nlao2/lab_1/lab_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/nlao2/lab_1/lab_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/nlao2/lab_1/lab_1.srcs/sources_1/new/Intro.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc //ad.uillinois.edu/engr-ews/nlao2/Downloads/xem7310_v1.xdc
set_property used_in_implementation false [get_files //ad.uillinois.edu/engr-ews/nlao2/Downloads/xem7310_v1.xdc]


synth_design -top intro -part xc7a75tfgg484-1


write_checkpoint -force -noxdef intro.dcp

catch { report_utilization -file intro_utilization_synth.rpt -pb intro_utilization_synth.pb }
